// api/custody/v1/custody.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/custody/v1/custody.proto

package custodyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_api_custody_v1_custody_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_custody_v1_custody_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_api_custody_v1_custody_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransferRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *TransferRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_api_custody_v1_custody_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_custody_v1_custody_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_api_custody_v1_custody_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransferResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_custody_v1_custody_proto protoreflect.FileDescriptor

const file_api_custody_v1_custody_proto_rawDesc = "" +
	"\n" +
	"\x1capi/custody/v1/custody.proto\x12\n" +
	"custody.v1\"q\n" +
	"\x0fTransferRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"?\n" +
	"\x10TransferResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2W\n" +
	"\x0eCustodyService\x12E\n" +
	"\bTransfer\x12\x1b.custody.v1.TransferRequest\x1a\x1c.custody.v1.TransferResponseB)Z'andi-custodian/api/custody/v1;custodyv1b\x06proto3"

var (
	file_api_custody_v1_custody_proto_rawDescOnce sync.Once
	file_api_custody_v1_custody_proto_rawDescData []byte
)

func file_api_custody_v1_custody_proto_rawDescGZIP() []byte {
	file_api_custody_v1_custody_proto_rawDescOnce.Do(func() {
		file_api_custody_v1_custody_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_custody_v1_custody_proto_rawDesc), len(file_api_custody_v1_custody_proto_rawDesc)))
	})
	return file_api_custody_v1_custody_proto_rawDescData
}

var file_api_custody_v1_custody_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_custody_v1_custody_proto_goTypes = []any{
	(*TransferRequest)(nil),  // 0: custody.v1.TransferRequest
	(*TransferResponse)(nil), // 1: custody.v1.TransferResponse
}
var file_api_custody_v1_custody_proto_depIdxs = []int32{
	0, // 0: custody.v1.CustodyService.Transfer:input_type -> custody.v1.TransferRequest
	1, // 1: custody.v1.CustodyService.Transfer:output_type -> custody.v1.TransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_custody_v1_custody_proto_init() }
func file_api_custody_v1_custody_proto_init() {
	if File_api_custody_v1_custody_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_custody_v1_custody_proto_rawDesc), len(file_api_custody_v1_custody_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_custody_v1_custody_proto_goTypes,
		DependencyIndexes: file_api_custody_v1_custody_proto_depIdxs,
		MessageInfos:      file_api_custody_v1_custody_proto_msgTypes,
	}.Build()
	File_api_custody_v1_custody_proto = out.File
	file_api_custody_v1_custody_proto_goTypes = nil
	file_api_custody_v1_custody_proto_depIdxs = nil
}
