// api/custody/v1/custody.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/custody/v1/custody.proto

package custodyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustodyService_Transfer_FullMethodName = "/custody.v1.CustodyService/Transfer"
)

// CustodyServiceClient is the client API for CustodyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustodyServiceClient interface {
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
}

type custodyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustodyServiceClient(cc grpc.ClientConnInterface) CustodyServiceClient {
	return &custodyServiceClient{cc}
}

func (c *custodyServiceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, CustodyService_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustodyServiceServer is the server API for CustodyService service.
// All implementations must embed UnimplementedCustodyServiceServer
// for forward compatibility.
type CustodyServiceServer interface {
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	mustEmbedUnimplementedCustodyServiceServer()
}

// UnimplementedCustodyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustodyServiceServer struct{}

func (UnimplementedCustodyServiceServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedCustodyServiceServer) mustEmbedUnimplementedCustodyServiceServer() {}
func (UnimplementedCustodyServiceServer) testEmbeddedByValue()                        {}

// UnsafeCustodyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustodyServiceServer will
// result in compilation errors.
type UnsafeCustodyServiceServer interface {
	mustEmbedUnimplementedCustodyServiceServer()
}

func RegisterCustodyServiceServer(s grpc.ServiceRegistrar, srv CustodyServiceServer) {
	// If the following call panics, it indicates UnimplementedCustodyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustodyService_ServiceDesc, srv)
}

func _CustodyService_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustodyServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustodyService_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustodyServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustodyService_ServiceDesc is the grpc.ServiceDesc for CustodyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustodyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "custody.v1.CustodyService",
	HandlerType: (*CustodyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Transfer",
			Handler:    _CustodyService_Transfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/custody/v1/custody.proto",
}
